
img_datas =['C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\adrenal\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\adrenal_gland_left\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\adrenal_gland_left\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\adrenal_gland_left\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\adrenal_gland_right\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\adrenal_gland_right\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\adrenal_gland_right\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\aorta\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\aorta\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\aorta\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\bladder\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\bladder\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\colon\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\duodenum\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\duodenum\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\duodenum\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\esophagus\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\esophagus\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\esophagus\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\esophagus\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\femur_left\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\femur_right\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\gallbladder\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\gallbladder\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\gallbladder\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\gallbladder\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\inferior_vena_cava\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\inferior_vena_cava\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\intestine\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\kidney_left\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\kidney_left\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\kidney_left\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\kidney_left\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\kidney_right\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\kidney_right\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\kidney_right\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\kidney_right\\WORD',
            'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\left_adrenal_gland\\Amos',
            'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\right_adrenal_gland\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\liver\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\liver\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\liver\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\liver\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\pancreas\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\pancreas\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\pancreas\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\pancreas\\WORD',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\portal_vein_and_splenic_vein\\BTCV',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\postcava\\Amos', 'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\prostate\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\rectum\\WORD', 'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\spleen\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\spleen\\BTCV', 'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\spleen\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\spleen\\WORD', 'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\stomach\\Amos',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\stomach\\BTCV', 'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\stomach\\FLARE22',
             'C:\\pycharm workspace\\SAM-Med3D-main\\data\\sam3d_defaltcls_dataset\\stomach\\WORD']

# all_classes = [
#         "spleen",
#         "kidney_right",
#         "kidney_left",
#         "gallbladder",
#         "liver",
#         "stomach",
#         "pancreas",
#         "esophagus",
#
# ]


all_classes = [
"adrenal",
 "adrenal_gland_left",
 "adrenal_gland_right",
"aorta",
 "bladder",
 "colon",
 "duodenum",
 "esophagus",
 "femur_left",
 "femur_right",
 "gallbladder",
 "inferior_vena_cava",
 "intestine",
 "kidney_left",
 "kidney_right",
 "liver",
 "pancreas",
 "portal_vein_and_splenic_vein",
 "postcava",
 "prostate",
"rectum",
 "spleen",
 "stomach",
    'left_adrenal_gland',
    'right_adrenal_gland'

    ]


all_datasets = [
'BTCV',
 "FLARE22",
 "Amos",
 "WORD",
]